### PR TITLE
Made some changes and updated build system

### PR DESCRIPTION
**Pull request by andersc**
+ Print PAT/PMT information in debug mode only.
+ Created build for static library
+ Removed submodule and created external project instead (much simpler to maintain)
+ Updated readme
+ Made PAT/PMT public and created flags to see if they are valid

### CODE REVIEW

**Comment by andersc** [comment]
Added automatic build of the lib and executables..  The readme needs to be updated to match the badges on the master repository if merged.

**Comment by andersc** [comment]
Removed the _ prefixes as for C++ it's not recommended to be used ->

https://softwareengineering.stackexchange.com/questions/191828/might-starting-variables-members-with-an-underscore-puzzle-the-compiler

https://stackoverflow.com/questions/3136594/naming-convention-underscore-in-c-and-c-sharp-variables/20496955

**Comment by andersc** [comment]
Added prefixes following the rules ->
// Prefixes used
// m class member
// p pointer (*)
// r reference (&)
// l local scope

And changed to camelCase

**Comment by andersc** [comment]
The 'Multi TS-Packet demux-bug fixed' https://github.com/akanchi/mpegts/pull/6/commits/ae8b73a4783c589afe78bba6ae37fc5b9da7ad86

Should be cherrypicked and verified.

**Comment by akanchi** [comment]
> Removed the _ prefixes as for C++ it's not recommended to be used ->
> 
> https://softwareengineering.stackexchange.com/questions/191828/might-starting-variables-members-with-an-underscore-puzzle-the-compiler
> 
> https://stackoverflow.com/questions/3136594/naming-convention-underscore-in-c-and-c-sharp-variables/20496955

I prefer Google's code style
https://google.github.io/styleguide/cppguide.html#Variable_Names

**Comment by andersc** [comment]
Fully understand.. I will close this pull-request and continue working on my fork.. Will let you know if I find any bugs...  (BTW .. tnks for a great project! )

**Comment by akanchi** [comment]
Thanks, and I want to synchronize your changes to autobuild and CMakeLists.txt

**Pull request closed without merging**
